services:
  postgres:
    image: postgres:16
    container_name: yduqs_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yduqsdatabase
      POSTGRES_DB: yduqs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
